version: '3'
services:
    go:
        container_name: go
        build:
            context: .
            args: 
                - UID=${UID}
                - GID=${GID}
        tty: true
        volumes: 
            - ./src:/go/src
        ports:
            - "8080:8080"
