version: '3'
services:
    dev:
        container_name: dev
        build:
            context: .
            args: 
                - UID=${UID}
                - GID=${GID}
        tty: true
        volumes: 
            - ./src:/go/src
        ports:
            - "8080:8080"